EveTeslimDiyetServis/Models/Kurye.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace ETDS.Models
{
    public class Kurye
    {
        [Key]
        public int Id { get; set; }

        public int KullaniciId { get; set; }

        public int AsciId { get; set; }

        public string AsciAdi { get; set; }

        public virtual Kullanici Kullanici { get; set; }

       
    }
}

EveTeslimDiyetServis/Controllers/KuryeController.cs
using ETDS.Models;
using EveTeslimDiyetServis.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EveTeslimDiyetServis.Controllers
{
    public class KuryeController : Controller
    {
        ETDSContext cont = new ETDSContext();
        // GET: Kurye
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult ListSiparisAlinan()
        {
            var kullaniciAdi = (string)Session["kullanici_adi"];
            var kullanici = cont.Kullanici.Where(l => l.KullaniciAd.Equals(kullaniciAdi)).FirstOrDefault();
            // Sisteme giriş yapan kuryenin bulundugu ilde gelen siparişleri filtreliyoruz.
            var siparisList = cont.Siparis.Where(l => l.Kullanici.IlId == kullanici.IlId && l.DurumId == (int)EnumSiparisDurum.SiparisDagitimda).ToList().OrderByDescending(l => l.Tarih);
            return View(siparisList);
        }

        //Kullanıcı tarafında siparis durum bilgisinin guncellenmesi için eklenmiştir.
        public ActionResult SiparisOnay(int Id)
        {
            var siparis = cont.Siparis.Find(Id);
            return PartialView(siparis);
        }

        [HttpPost]
        public ActionResult SiparisOnay(Siparis siparis)
        {
            var siparisEdit = cont.Siparis.Find(siparis.Id);
            siparisEdit.DurumId = (int)EnumSiparisDurum.SiparisOnaylandi;
            cont.SaveChanges();
            return RedirectToAction("ListSiparisAlinan");
        }


        //Kuryeye gönderilen siparişlerin listelendiği ekrandır.
        public ActionResult ListSiparisTamamlanan()
        {
            var kullaniciAdi = (string)Session["kullanici_adi"];
            var kullanici = cont.Kullanici.Where(l => l.KullaniciAd.Equals(kullaniciAdi)).FirstOrDefault();
            // Sisteme giriş yapan kuryenin bulundugu ilde gelen siparişleri filtreliyoruz.
            var siparisList = cont.Siparis.Where(l => l.Kullanici.IlId == kullanici.IlId && l.DurumId == (int)EnumSiparisDurum.SiparisOnaylandi).ToList().OrderByDescending(l => l.Tarih);
            return View(siparisList);
        }

    }
}

EveTeslimDiyetServis/Views/Kurye/ListSiparisAlinan.cshtml
@model IEnumerable<ETDS.Models.Siparis>
@{
    ViewBag.Title = "ListSiparis";
    Layout = "~/Views/Shared/_LayoutKurye.cshtml";
}

<div>
    <fieldset>
        <legend>Alınan Siparişler</legend>
        <div class="alert alert-info">Lütfen teslimini yaptığınız siparişleri onaylayın.</div>
        <table class="table table-bordered">
            <tr>
                <th>
                    @Html.DisplayName("Sipariş No")
                </th>
                <th>
                    @Html.DisplayName("Ad")
                </th>
                <th>
                    @Html.DisplayName("Soyad")
                </th>
                <th>
                    @Html.DisplayName("Adres")
                </th>
                <th>
                    @Html.DisplayName("Tarih")
                </th>
                <th>
                    @Html.DisplayName("Durum")
                </th>
                <th></th>
            </tr>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Id)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Kullanici.Ad)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Kullanici.Soyad)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Kullanici.Adres)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Tarih)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.SiparisDurum.Durum)
                    </td>
                    <td>
                        @Html.ActionLink("Siparişi Onayla", "SiparisOnay", new { id = item.Id }, new { @class = "btn btn-info", data_toggle = "modal", data_target = "#siparisOnay", data_dismiss = "modal", data_backdrop = "static", data_keyboard = "false" })
                    </td>
                </tr>
            }

        </table>
    </fieldset>
</div>
<div class="modal fade" tabindex="-1" role="dialog" id="siparisOnay">
    <div class="modal-dialog">
        <div class="modal-body">
            <div class="modal-content">
                @Html.Partial("SiparisOnay", new ETDS.Models.Siparis(), new ViewDataDictionary { { "Id", Model.GetEnumerator() } })
            </div>
        </div>
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

EveTeslimDiyetServis/Views/Kurye/ListSiparisTamamlanan.cshtml
@model IEnumerable<ETDS.Models.Siparis>
@{
    ViewBag.Title = "ListSiparis";
    Layout = "~/Views/Shared/_LayoutKurye.cshtml";
}

<div>
    <fieldset>
        <legend>Tamamlanan Siparişler</legend>
        <table class="table table-bordered">
            <tr>
                <th>
                    @Html.DisplayName("Sipariş No")
                </th>
                <th>
                    @Html.DisplayName("Ad")
                </th>
                <th>
                    @Html.DisplayName("Soyad")
                </th>
                <th>
                    @Html.DisplayName("Adres")
                </th>
                <th>
                    @Html.DisplayName("Tarih")
                </th>
                <th>
                    @Html.DisplayName("Durum")
                </th>
            </tr>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Id)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Kullanici.Ad)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Kullanici.Soyad)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Kullanici.Adres)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Tarih)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.SiparisDurum.Durum)
                    </td>
                </tr>
            }

        </table>
    </fieldset>
</div>

EveTeslimDiyetServis/Views/Kurye/SiparisOnay.cshtml
@model ETDS.Models.Siparis
@using (Html.BeginForm("SiparisOnay", "Kurye", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">Sipariş Onay</h3>
        </div>
        <div class="panel-body">
            <div class="form-group">
                <p>Siparişi teslim ettiğinizi onaylıyor musunuz ?</p>
                @Html.HiddenFor(model => model.Id)
            </div>

            <div class="pull-right clearfix">
                <input type="submit" value="ONAYLA" class="btn btn-primary btn-md" />  <a href="@Url.Action("ListSiparisAlinan", "Kurye")" class="btn btn-default btn-md">İPTAL</a>
            </div>
        </div>
    </div>
}