EveTeslimDiyetServis/Models/Kullanici.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace ETDS.Models
{
    public class Kullanici
    {
        [Key]
        public int Id { get; set; }
        public string Ad { get; set; }
        public string Soyad { get; set; }
        [Required]
        public string KullaniciAd { get; set; }
        public string EPosta { get; set; }
        public string Sifre { get; set; }
        public string Adres { get; set; }
        public string Gsm { get; set; }
        public double? Boy { get; set; }
        public double? Kilo { get; set; }
        public string Cinsiyet { get; set; }
        public string ProfilResmi { get; set; }
        public int? IlId { get; set; }
        [Required]
        public int RolId { get; set; }

        public virtual Rol Rol {get; set;}

        public virtual Il Il { get; set; }
    }
}

EveTeslimDiyetServis/Controllers/KullaniciController.cs
using ETDS.Models;
using EveTeslimDiyetServis.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EveTeslimDiyetServis.Controllers
{
    public class KullaniciController : Controller
    {
        ETDSContext cont = new ETDSContext();

        public ActionResult HomePage()
        {
            return View();
        }

        // GET: Kullanici
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Prizes()
        {
            return View();
        }

        public ActionResult About()
        {
            return View();
        }

        // GET: Kullanici
        public ActionResult Profil()
        {
            var kullaniciAdi = (string)Session["kullanici_adi"];
            var kullanici = cont.Kullanici.Where(l => l.KullaniciAd.Equals(kullaniciAdi)).FirstOrDefault();
            return View(kullanici);
        }

        // GET: Kullanici
        public ActionResult EditProfil()
        {
            var kullaniciAdi = (string)Session["kullanici_adi"];
            var kullanici = cont.Kullanici.Where(l => l.KullaniciAd.Equals(kullaniciAdi)).FirstOrDefault();
            var ilList = cont.Il.ToList().Select(k => new SelectListItem
            {
                Selected = false,
                Text = k.Ad,
                Value = k.Id.ToString()
            }).ToList();
            ViewBag.IlList = ilList;
            return View(kullanici);
        }

        [HttpPost]
        public ActionResult EditProfil(Kullanici kullanici, HttpPostedFileBase ProfileImage)
        {
            if (ProfileImage != null &&
                (ProfileImage.ContentType == "image/jpeg" ||
                    ProfileImage.ContentType == "image/jpg" ||
                    ProfileImage.ContentType == "image/png"))
            {
                string filename = $"user_{kullanici.Id}.{ProfileImage.ContentType.Split('/')[1]}";

                ProfileImage.SaveAs(Server.MapPath($"~/Images/{filename}"));
                kullanici.ProfilResmi = filename;
            }

            var kullaniciEdit = cont.Kullanici.Find(kullanici.Id);
            if (kullaniciEdit != null)
            {
                kullaniciEdit.Ad = kullanici.Ad;
                kullaniciEdit.Soyad = kullanici.Soyad;
                kullaniciEdit.KullaniciAd = kullanici.KullaniciAd;
                kullaniciEdit.Adres = kullanici.Adres;
                kullaniciEdit.Boy = kullanici.Boy;
                kullaniciEdit.Cinsiyet = kullanici.Cinsiyet;
                kullaniciEdit.EPosta = kullanici.EPosta;
                kullaniciEdit.Gsm = kullanici.Gsm;
                kullaniciEdit.IlId = kullanici.IlId;
                kullaniciEdit.Kilo = kullanici.Kilo;
                kullaniciEdit.ProfilResmi = kullanici.ProfilResmi;
            }

            cont.SaveChanges();
            var ilList = cont.Il.ToList().Select(k => new SelectListItem
            {
                Selected = true,
                Text = k.Ad,
                Value = k.Id.ToString()
            }).ToList();
            ViewBag.IlList = ilList;
            ViewBag.Success = "İşleminiz başarıyla gerçekleştirilmiştir.";
            return View(kullanici);
        }

        public ActionResult CreateSiparis()
        {
            var kullaniciAdi = (string)Session["kullanici_adi"];
            var kullanici = cont.Kullanici.Where(l => l.KullaniciAd.Equals(kullaniciAdi)).FirstOrDefault();

            var paketList = cont.Paket.ToList().Select(k => new SelectListItem
            {
                Selected = false,
                Text = k.Aciklama,
                Value = k.Id.ToString()
            }).ToList();
            ViewBag.PaketList = paketList;

            var ogunList = cont.Ogun.ToList().Select(k => new SelectListItem
            {
                Selected = false,
                Text = k.Aciklama,
                Value = k.Id.ToString()
            }).ToList();
            ViewBag.OgunList = ogunList;
            SelectListItem adres = new SelectListItem();
            adres.Selected = false;
            adres.Text = kullanici.Adres;
            adres.Value = kullanici.Adres;
            var adresList = new List<SelectListItem>();
            adresList.Add(adres);
            ViewBag.AdresList = adresList;

            Siparis siparis = new Siparis();
            siparis.KullaniciId = kullanici.Id;
            return View(siparis);
        }

        [HttpPost]
        public ActionResult CreateSiparis(Siparis siparis)
        {
            var kullaniciAdi = (string)Session["kullanici_adi"];
            var kullanici = cont.Kullanici.Where(l => l.KullaniciAd.Equals(kullaniciAdi)).FirstOrDefault();

            var paketList = cont.Paket.ToList().Select(k => new SelectListItem
            {
                Selected = false,
                Text = k.Aciklama,
                Value = k.Id.ToString()
            }).ToList();
            ViewBag.PaketList = paketList;

            var ogunList = cont.Ogun.ToList().Select(k => new SelectListItem
            {
                Selected = false,
                Text = k.Aciklama,
                Value = k.Id.ToString()
            }).ToList();
            ViewBag.OgunList = ogunList;
            SelectListItem adres = new SelectListItem();
            adres.Selected = false;
            adres.Text = kullanici.Adres;
            adres.Value = kullanici.Adres;
            var adresList = new List<SelectListItem>();
            adresList.Add(adres);
            ViewBag.AdresList = adresList;

            siparis.Tarih = DateTime.Now;
            siparis.DurumId = (int)EnumSiparisDurum.SiparisAlindi;
            cont.Siparis.Add(siparis);
            cont.SaveChanges();
            ViewBag.Success = "Siparişiniz alınmıştır. Siparişlerim bölmünden kontrolünü sağlayabilirsiniz.";
            return View(siparis);
        }

        public ActionResult ListSiparis()
        {
            var kullaniciAdi = (string)Session["kullanici_adi"];
            var kullanici = cont.Kullanici.Where(l => l.KullaniciAd.Equals(kullaniciAdi)).FirstOrDefault();

            var siparisList = cont.Siparis.Where(l => l.KullaniciId == kullanici.Id).ToList();
            return View(siparisList);
        }

        public ActionResult GunlukKalori()
        {
            return View();
        }
        public ActionResult IdealKilo()
        {
            return View();
        }

        public ActionResult BelRisk()
        {
            return View();
        }


        public ActionResult BelKalca()
        {
            return View();
        }

        public ActionResult VucutKitle()
        {
            return View();
        }

    }
}

EveTeslimDiyetServis/Views/Kullanici/About.cshtml
@{
    ViewBag.Title = "About";
    Layout = "~/Views/Shared/_LayoutKullanici.cshtml";
}

<div class="fw pageTitleAll">
    <div class="container">
        <div class="fw pageTitle">
            <h1 class="title">HAKKIMIZDA</h1>
        </div><!--.pageTitle-->
    </div><!--.container-->
</div><!--.pageTitleAll-->
<div class="container">
    <div class="fw pageContent">
        <img src="~/Images/yya.jpg" />
        <p>Günümüz dünyasında obezite tehdidi hızla yayılmaktadır. İnsanların vakit tasarrufu sebebi ile yeme alışkanlıkları gün geçtikçe hızlı hazırlanan kolay temin edilebilen yiyeceklere doğru yönelmektedir. Bu ihtiyaçlar fast food kültürünü hızla hayatlarımızın içerisine dahil etmiş durumda. Bu tarz düzensiz beslenme şekilleri hepimizin hayatında yer edinmekle birlikte için risk teşkil etmekte. Bu nedenle gerek sağlıklı beslenme alışkanlığını sürdürmek isteyen gerekse 	bir diyetisyen müdahalesi ile sağlıklı beslenme alışkanlığı edinmek isteyen insanlar için sağlıklı besin temini ihtiyaç haline gelmiştir. Bu ihtiyaçlar doğrultusunda Eve Teslim Diyet Servisi ortaya çıkmıştır. </p>
        <p>Yinelenen bir sayfa içeriğinin okuyucunun dikkatini dağıttığı bilinen bir gerçektir. Lorem Ipsum kullanmanın amacı, sürekli 'buraya metin gelecek, buraya metin gelecek' yazmaya kıyasla daha dengeli bir harf dağılımı sağlayarak okunurluğu artırmasıdır. Şu anda birçok masaüstü yayıncılık paketi ve web sayfa düzenleyicisi, varsayılan mıgır metinler olarak Lorem Ipsum kullanmaktadır. Ayrıca arama motorlarında 'lorem ipsum' anahtar sözcükleri ile arama yapıldığında henüz tasarım aşamasında olan çok sayıda site listelenir. Yıllar içinde, bazen kazara, bazen bilinçli olarak (örneğin mizah katılarak), çeşitli sürümleri geliştirilmiştir.</p>
    </div><!--.pageContent-->
</div><!--.container-->

EveTeslimDiyetServis/Views/Kullanici/BelKalca.cshtml
@{
    ViewBag.Title = "BelKalca";
    Layout = "~/Views/Shared/_LayoutKullanici.cshtml";
}



<div class="fw pageTitleAll">
    <div class="container">
        <div class="fw pageTitle">
            <h1 class="title">BEL KALÇA ORANI HESAPLAMA</h1>
        </div><!--.pageTitle-->
    </div><!--.container-->
</div><!--.pageTitleAll-->

<div class="container">
    <div class="fw formBox">
        <ul>

            <li><span class="title">BEL ÇEVRESİ (CM)</span><input type="number" placeholder="" class="formText" pattern="[0-9]*" id="belcevresi2" /></li>
            <li><span class="title">KALÇA ÇEVRESİ (CM)</span><input type="number" placeholder="" class="formText" pattern="[0-9]*" id="kalcasevresi" /></li>
            <li><span class="title">CİNSİYETİNİZ</span><select class="formSelect" id="gender4"><option value="">Seçiniz</option><option value="1">Erkek</option><option value="2">Kadın</option></select></li>
            <li><a href="javascript:void(0)" class="formSubmita" id="calculaterisk">HESAPLA</a></li>
        </ul>
    </div><!--.formBox-->
    <div class="fw formResult">
        <p class="caloriebox" id="idealobsk"></p>
        <p id="obsktext" style="font-size:14px;padding:0px;color:red"></p>
    </div><!--.formResult-->
</div><!--.container-->

EveTeslimDiyetServis/Views/Kullanici/BelRisk.cshtml
@{
    ViewBag.Title = "BelRisk";
    Layout = "~/Views/Shared/_LayoutKullanici.cshtml";
}



<div class="fw pageTitleAll">
    <div class="container">
        <div class="fw pageTitle">
            <h1 class="title">BEL ÇEVRESİNE GÖRE RİSK HESAPLAMA</h1>
        </div><!--.pageTitle-->
    </div><!--.container-->
</div><!--.pageTitleAll-->

<div class="container">
    <div class="fw formBox">
        <ul>

            <li><span class="title">BEL ÇEVRESİ (CM)</span><input type="number" placeholder="" class="formText" pattern="[0-9]*" id="belcevresi1belcev" /></li>
            <li><span class="title">CİNSİYETİNİZ</span><select class="formSelect" id="genderbelcev"><option value="">Seçiniz</option><option value="1">Erkek</option><option value="2">Kadın</option></select></li>
            <li><a href="javascript:void(0)" class="formSubmita" id="calculateobsbelcev">HESAPLA</a></li>
        </ul>
    </div><!--.formBox-->
    <div class="fw formResult">
        <p class="caloriebox" id="idealobs"></p>
        <p id="obstext" style="font-size:14px;padding:0px;color:red"></p>
    </div><!--.formResult-->
</div><!--.container-->

EveTeslimDiyetServis/Views/Kullanici/CreateSiparis.cshtml
@model ETDS.Models.Siparis
@{
    ViewBag.Title = "CreateSiparis";
    Layout = "~/Views/Shared/_LayoutKullanici.cshtml";
}


@using (Html.BeginForm("CreateSiparis", "Kullanici", FormMethod.Post))
{
    <div class="fw pageTitleAll">
        <div class="container">
            <div class="fw pageTitle">
                <h1 class="title">Sipariş Ver</h1>
            </div><!--.pageTitle-->
        </div><!--.container-->
    </div><!--.pageTitleAll-->

    @Html.ValidationSummary(false)

    <div class="container">
        <div class="fw formBox">
            @if (ViewBag.Error != null)
            {
                <div class="alert alert-danger">@ViewBag.Error</div>
            }
            @if (ViewBag.Success != null)
            {
                <div class="alert alert-success">@ViewBag.Success</div>
            }

            <div class="form-horizontal">
                @Html.HiddenFor(model => model.KullaniciId)

                <div class="col-md-offset-2 col-md-6">
                    <div class="form-group">
                        @Html.Label("Paket", htmlAttributes: new { @class = "control-label col-md-3" })
                        <div class="col-md-9">
                            @Html.DropDownList("PaketId", (List<SelectListItem>)ViewBag.PaketList, "Paket Seçiniz..", new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.PaketId)
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.Label("Öğün", htmlAttributes: new { @class = "control-label col-md-3" })
                        <div class="col-md-9">
                            @Html.DropDownList("OgunId", (List<SelectListItem>)ViewBag.OgunList, "Öğün Seçiniz..", new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.OgunId)
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.Label("Adres", htmlAttributes: new { @class = "control-label col-md-3" })
                        <div class="col-md-9">
                            @Html.DropDownList("Adres", (List<SelectListItem>)ViewBag.AdresList, "Adres Seçiniz..", new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.Adres)
                        </div>
                    </div>
                    <br />
                    <br />
                    <div class="form-group pull-right col-md-offset-8">
                        <a href="@Url.Action("Index","Kullanici")" class="btn btn-default">İPTAL</a> <button type="submit" class="btn btn-danger" onclick="KullaniciEkle_click">KAYIT OL</button>
                    </div>
                </div>
            </div><!--.formBox-->
        </div><!--.container-->
    </div>
}

EveTeslimDiyetServis/Views/Kullanici/EditProfil.cshtml
@model ETDS.Models.Kullanici

@{
    ViewBag.Title = "Profil Düzenle";
    Layout = "~/Views/Shared/_LayoutKullanici.cshtml";
}

<link href="~/Content/validation-summary.css" rel="stylesheet" />

<div class="container">

    <div class="row">
        <h2>@ViewBag.Title</h2>
        <hr />
    </div>

    @if (ViewBag.Success != null)
    {
        <div class="alert alert-success">@ViewBag.Success</div>
    }

    <div class="row">
        @using (Html.BeginForm("EditProfil", "Kullanici", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            <div class="form-horizontal">

                <div class="col-md-3">
                    @if (Model.ProfilResmi == null)
                    {
                        <img src="~/Images/user.png" class="img-circle" width="128" height="128" />
                    }
                    else
                    {
                        <img src="~/Images/@Model.ProfilResmi" class="img-circle" width="128" height="128" />
                    }

                    @Html.HiddenFor(model => model.ProfilResmi)
                    <br /><br />
                    <input type="file" name="ProfileImage" id="ProfileImage" class="form-control" /><br />
                    <span class="glyphicon glyphicon-info-sign">&nbsp;</span>
                    <span><i>Lütfen jpg, jpeg ya da png formatı kullanın.</i></span>
                </div>

                <div class="col-md-5">

                    @Html.ValidationSummary(false)
                    @Html.HiddenFor(model => model.Id)

                    <div class="form-group">
                        @Html.LabelFor(model => model.Ad, htmlAttributes: new { @class = "control-label col-md-3" })
                        <div class="col-md-9">
                            @Html.EditorFor(model => model.Ad, new { htmlAttributes = new { @class = "form-control" } })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Soyad, htmlAttributes: new { @class = "control-label col-md-3" })
                        <div class="col-md-9">
                            @Html.EditorFor(model => model.Soyad, new { htmlAttributes = new { @class = "form-control" } })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.KullaniciAd, htmlAttributes: new { @class = "control-label col-md-3" })
                        <div class="col-md-9">
                            @Html.EditorFor(model => model.KullaniciAd, new { htmlAttributes = new { @class = "form-control" } })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Sifre, htmlAttributes: new { @class = "control-label col-md-3" })
                        <div class="col-md-9">
                            @Html.EditorFor(model => model.Sifre, new { htmlAttributes = new { @class = "form-control", type = "password" } })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.EPosta, htmlAttributes: new { @class = "control-label col-md-3" })
                        <div class="col-md-9">
                            @Html.EditorFor(model => model.EPosta, new { htmlAttributes = new { @class = "form-control" } })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Cinsiyet, htmlAttributes: new { @class = "control-label col-md-3" })
                        <div class="col-md-9">
                            @Html.DropDownListFor(model => model.Cinsiyet, new SelectList(new string[] { "Erkek", "Kadın" }, ""), htmlAttributes: new { @class = "form-control" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.Label("İl", htmlAttributes: new { @class = "control-label col-md-3" })
                        <div class="col-md-9">
                            @Html.DropDownList("IlId", (List<SelectListItem>)ViewBag.IlList, "İl Seçiniz..", new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.IlId)
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.Label("Boy(cm)", htmlAttributes: new { @class = "control-label col-md-3" })
                        <div class="col-md-9">
                            @Html.EditorFor(model => model.Boy, new { htmlAttributes = new { @class = "form-control" } })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Kilo, htmlAttributes: new { @class = "control-label col-md-3" })
                        <div class="col-md-9">
                            @Html.EditorFor(model => model.Kilo, new { htmlAttributes = new { @class = "form-control" } })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Gsm, htmlAttributes: new { @class = "control-label col-md-3" })
                        <div class="col-md-9">
                            @Html.EditorFor(model => model.Gsm, new { htmlAttributes = new { @class = "form-control" } })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Adres, htmlAttributes: new { @class = "control-label col-md-3" })
                        <div class="col-md-9">
                            @Html.EditorFor(model => model.Adres, new { htmlAttributes = new { @class = "form-control" } })
                        </div>
                    </div>


                    <div class="form-group">
                        <div class="pull-right col-md-offset-6">
                            @Html.ActionLink("Geri Dön", "Profil", "Kullanici", null, new { @class = "btn btn-default" })
                            <input type="submit" value="Kaydet" class="btn btn-danger" />
                        </div>
                    </div>

                </div>

                <div class="col-md-4">
                    &nbsp;
                </div>
            </div>
        }
    </div>

</div>

EveTeslimDiyetServis/Views/Kullanici/GunlukKalori.cshtml
@{
    ViewBag.Title = "GunlukKalori";
    Layout = "~/Views/Shared/_LayoutKullanici.cshtml";
}

<div class="fw pageTitleAll">
    <div class="container">
        <div class="fw pageTitle">
            <h1 class="title">GÜNLÜK KALORİ İHTİYACI HESAPLAMA</h1>
        </div><!--.pageTitle-->
    </div><!--.container-->
</div><!--.pageTitleAll-->

<div class="container">
    <div class="fw formBox">
        <ul>

            <li><span class="title">YAŞ</span><input type="number" pattern="[0-9]*" class="formText" id="yasideal" /></li>
            <li><span class="title">BOYUNUZ (CM)</span><input type="number" placeholder="" class="formText" pattern="[0-9]*" id="boyunuzideal" /></li>
            <li><span class="title">KİLONUZ (KG)</span><input type="number" placeholder="" class="formText" pattern="[0-9]*" id="kilonuzideal1" /></li>
            <li><span class="title">CİNSİYETİNİZ</span><select class="formSelect" id="cinsiyetideal"><option value="">Seçiniz</option><option value="1">Erkek</option><option value="2">Kadın</option></select></li>
            <li><a href="javascript:void(0)" class="formSubmita" id="calculateideal">HESAPLA</a></li>
        </ul>
    </div><!--.formBox-->
    <div class="fw formResult">
        <p class="caloriebox1" id="idealvalue"></p>
    </div><!--.formResult-->
</div><!--.container-->

EveTeslimDiyetServis/Views/Kullanici/IdealKilo.cshtml
@{
    ViewBag.Title = "IdealKilo";
    Layout = "~/Views/Shared/_LayoutKullanici.cshtml";
}

<div class="fw pageTitleAll">
    <div class="container">
        <div class="fw pageTitle">
            <h1 class="title">İDEAL KİLO HESAPLAMA</h1>
        </div><!--.pageTitle-->
    </div><!--.container-->
</div><!--.pageTitleAll-->

<div class="container">
    <div class="fw formBox">
        <ul>

            <li><span class="title">YAŞ</span><input type="number" pattern="[0-9]*" class="formText" id="yasideal" /></li>
            <li><span class="title">BOYUNUZ (CM)</span><input type="number" placeholder="" class="formText" pattern="[0-9]*" id="boyunuzideal" /></li>
            <li><span class="title">KİLONUZ (KG)</span><input type="number" placeholder="" class="formText" pattern="[0-9]*" id="kilonuzideal1" /></li>
            <li><span class="title">CİNSİYETİNİZ</span><select class="formSelect" id="cinsiyetideal"><option value="">Seçiniz</option><option value="1">Erkek</option><option value="2">Kadın</option></select></li>
            <li><a href="javascript:void(0)" class="formSubmita" id="calculateideal">HESAPLA</a></li>
        </ul>
    </div><!--.formBox-->
    <div class="fw formResult">
        <p class="caloriebox1" id="idealvalue"></p>
    </div><!--.formResult-->
</div><!--.container-->

EveTeslimDiyetServis/Views/Kullanici/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutKullanici.cshtml";
}

<div class="col-md-offset-3">
    <div class="h2">Eve Teslim Diyet Servisine Hoşgeldiniz..!</div>
    <p class="lead">Sistem üzerinden sipariş vermek için lütfen kullanıcı bilgilrinizi eksiksiz bir şekilde doldurunuz.</p>
    <p><a class="btn btn-lg btn-success" href="@Url.Action("Profil","Kullanici")" role="button">Profile Git</a></p>
</div>

EveTeslimDiyetServis/Views/Kullanici/ListSiparis.cshtml
@model IEnumerable<ETDS.Models.Siparis>
@{
    ViewBag.Title = "ListSiparis";
    Layout = "~/Views/Shared/_LayoutKullanici.cshtml";
}

<div class="fw pageTitleAll">
    <div class="container">
        <div class="fw pageTitle">
            <h1 class="title">Siparişlerim</h1>
        </div><!--.pageTitle-->
    </div><!--.container-->
</div><!--.pageTitleAll-->

<div class="container">
    @*<legend>Siparişlerim</legend>*@
    <table class="table table-bordered">
        <tr>
            <th>
                @Html.DisplayName("Sipariş No")
            </th>
            <th>
                @Html.DisplayName("Paket(cal)")
            </th>
            <th>
                @Html.DisplayName("Öğün")
            </th>
            <th>
                @Html.DisplayName("İl")
            </th>
            <th>
                @Html.DisplayName("Tarih")
            </th>
            <th>
                @Html.DisplayName("Durum")
            </th>
        </tr>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Id)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Paket.Aciklama)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Ogun.Aciklama)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Kullanici.Il.Ad)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Tarih)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.SiparisDurum.Durum)
                </td>
            </tr>
        }

    </table>
</div>

EveTeslimDiyetServis/Views/Kullanici/Profil.cshtml
@model ETDS.Models.Kullanici
@{
    ViewBag.Title = "Profiliniz";
    Layout = "~/Views/Shared/_LayoutKullanici.cshtml";
}
}

<div class="container">

    <div class="row">
        <h2>@ViewBag.Title</h2>
        <hr />
    </div>

    <div class="row">

        <div class="col-md-2">
            @if (Model.ProfilResmi == null)
            {
                <img src="~/Images/user.png" class="img-circle" width="128" height="128" />
            }
            else
            {
                <img src="~/Images/@Model.ProfilResmi" class="img-circle" width="128" height="128" />
            }
        </div>

        <div class="col-md-8">
            <br />
            <h5><b>Kullanıcı Adı : </b>@Model.KullaniciAd</h5>
            <h5><b>Kullanıcı E-posta : </b>@Model.EPosta</h5>
            <br />
            <h5><a href="#">Daha Fazla... </a></h5>
        </div>
        <div class="col-md-2 text-right">
            <div class="btn-group">
                <a class="btn dropdown-toggle btn-info" data-toggle="dropdown" href="#">
                    <span class="glyphicon glyphicon-cog">
                        &nbsp;
                        Options
                    </span>
                </a>
                <ul class="dropdown-menu">
                    <li>
                        <a href="@Url.Action("EditProfil","Kullanici")">
                            <span class="glyphicon glyphicon-edit">&nbsp;</span>
                            Düzenle
                        </a>
                    </li>

                    <li>
                        <a href="@Url.Action("DeleteProfile")" onclick="return confirm('Hesabınızı silmek istediğinize emin misiniz?');">
                            <span class="glyphicon glyphicon-trash">&nbsp;</span>
                            Sil
                        </a>
                    </li>
                </ul>
            </div>

        </div>
    </div>
</div>

EveTeslimDiyetServis/Views/Kullanici/VucutKitle.cshtml
@{
    ViewBag.Title = "VucutKitle";
    Layout = "~/Views/Shared/_LayoutKullanici.cshtml";
}

<div class="fw pageTitleAll">
    <div class="container">
        <div class="fw pageTitle">
            <h1 class="title">VÜCUT KİTLE İNDEKSİ HESAPLAMA</h1>
        </div><!--.pageTitle-->
    </div><!--.container-->
</div><!--.pageTitleAll-->

<div class="container">
    <div class="fw formBox">
        <ul>

            <li><span class="title">KİLONUZ (KG)</span><input type="number" placeholder="" class="formText" pattern="[0-9]*" id="kilo" /></li>
            <li><span class="title">BOYUNUZ (CM)</span><input type="number" placeholder="" class="formText" pattern="[0-9]*" id="boy" /></li>
            <li><a href="javascript:void(0)" class="formSubmita" id="calculatebmi">HESAPLA</a></li>
        </ul>
    </div><!--.formBox-->
    <div class="fw formResult">
        <p class="caloriebox" id="bmivalue"></p>
        <p id="bmitext" style="font-size:14px;padding:0px;color:red"></p>
    </div><!--.formResult-->
</div><!--.container-->