EveTeslimDiyetServis/Models/Asci.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace ETDS.Models
{
    public class Asci
    {
        [Key]
        public int Id { get; set; }
        public int KullaniciId { get; set; }

        public virtual Kullanici Kullanici { get; set; }
    }
}

EveTeslimDiyetServis/Controllers/AsciController.cs
using ETDS.Models;
using EveTeslimDiyetServis.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EveTeslimDiyetServis.Controllers
{
    public class AsciController : Controller
    {
        ETDSContext cont = new ETDSContext();
        // GET: Menu
        public ActionResult Index()
        {
            return View();
        }
        // GET: Menu
        public ActionResult ListSiparisAlinan()
        {
            var kullaniciAdi = (string)Session["kullanici_adi"];
            var kullanici = cont.Kullanici.Where(l => l.KullaniciAd.Equals(kullaniciAdi)).FirstOrDefault();
            // Sisteme giriş yapan aşçının bulundugu ilde gelen siparişleri filtreliyoruz.
            var siparisList = cont.Siparis.Where(l => l.Kullanici.IlId == kullanici.IlId && l.DurumId !=(int)EnumSiparisDurum.SiparisOnaylandi).ToList().OrderByDescending(l=>l.Tarih);
            return View(siparisList);
        }
        //Kullanıcı tarafında siparis durum bilgisinin guncellenmesi için eklenmiştir.
        public ActionResult SiparisOnay(int Id)
        {
            var siparis = cont.Siparis.Find(Id);
            return PartialView(siparis);
        }

        [HttpPost]
        public ActionResult SiparisOnay(Siparis siparis)
        {
            var siparisEdit = cont.Siparis.Find(siparis.Id);
            siparisEdit.DurumId = (int)EnumSiparisDurum.SiparisHazirlaniyor;
            cont.SaveChanges();
            return RedirectToAction("ListSiparisAlinan");
        }

        public ActionResult SiparisGonder(int Id)
        {
            var siparis = cont.Siparis.Find(Id);
            var kullaniciAdi = (string)Session["kullanici_adi"];
            var kullanici = cont.Kullanici.Where(l => l.KullaniciAd.Equals(kullaniciAdi)).FirstOrDefault();

            var siparisList = cont.Siparis.ToList().Select(k => new SelectListItem
            {
                Selected = true,
                Text = k.Id.ToString(),
                Value = k.Id.ToString()
            }).ToList();         
            ViewBag.SiparisList = siparisList;
            //Aşçının bulundugu ilde bulunan kryelerin listelenmesini sağlıyoruz.
            var kuryeList = cont.Kurye.Where(l=>l.Kullanici.IlId==kullanici.IlId).ToList().Select(k => new SelectListItem
            {
                Selected = true,
                Text = k.Kullanici.Ad.ToString()+" "+ k.Kullanici.Soyad.ToString(),
                Value = k.Id.ToString()
            }).ToList();
            ViewBag.KuryeList = kuryeList;
            return View(siparis);
        }

        [HttpPost]
        public ActionResult SiparisGonder(Siparis siparis)
        {
            var siparisEdit = cont.Siparis.Find(siparis.Id);
            siparisEdit.DurumId = (int)EnumSiparisDurum.SiparisDagitimda;
            cont.SaveChanges();
            return RedirectToAction("ListSiparisAlinan");
        }

        //Kuryeye gönderilen siparişlerin listelendiği ekrandır.
        public ActionResult ListSiparisTamamlanan()
        {
            var kullaniciAdi = (string)Session["kullanici_adi"];
            var kullanici = cont.Kullanici.Where(l => l.KullaniciAd.Equals(kullaniciAdi)).FirstOrDefault();
            // Sisteme giriş yapan aşçının bulundugu ilde gelen siparişleri filtreliyoruz.
            var siparisList = cont.Siparis.Where(l => l.Kullanici.IlId == kullanici.IlId && l.DurumId ==(int)EnumSiparisDurum.SiparisDagitimda).ToList().OrderByDescending(l => l.Tarih);
            return View(siparisList);
        }


        //Kuryeye gönderilen siparişlerin listelendiği ekrandır.
        public ActionResult ListMenu()
        {
            var kullaniciAdi = (string)Session["kullanici_adi"];
            var kullanici = cont.Kullanici.Where(l => l.KullaniciAd.Equals(kullaniciAdi)).FirstOrDefault();
            // Sisteme giriş yapan aşçının bulundugu ilde gelen menuleri filtreliyoruz.
            var menuList = cont.Menu.Where(l => l.Diyetisyen.Kullanici.IlId == kullanici.IlId).ToList().OrderByDescending(l => l.MenuTarih);
            return View(menuList);
        }

        //Ascinin menulerin içeriğini goruntuledıgı actiondır.
        public ActionResult MenuIcerik(int Id)
        {
            ViewBag.MenuId = Id;
            ViewBag.MenuAd = cont.Menu.Where(l => l.Id == Id).Select(l => l.Ad).FirstOrDefault();
            var yemekList = cont.YemekMenu.Where(l => l.MenuId == Id).ToList();
            return View(yemekList);
        }

    }
}

EveTeslimDiyetServis/Views/Asci/ListMenu.cshtml
@model IEnumerable<ETDS.Models.Menu>

@{
    ViewBag.Title = "MenuList";
    Layout = "~/Views/Shared/_LayoutAsci.cshtml";
}

<fieldset>
    <legend>Menüler</legend>
    <table class="table table-bordered table-striped">
        <tr>
            <th>

            </th>
            <th>
                @Html.DisplayName("Ad")
            </th>
            <th>
                @Html.DisplayName("Diyetisyen")
            </th>
            <th>
                @Html.DisplayName("Öğün")
            </th>
            <th>
                @Html.DisplayName("Paket")
            </th>
            <th>
                @Html.DisplayName("Oluşturulma Tarihi")
            </th>
            <th></th>
        </tr>
        @{int rowNo = 0;}
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @(rowNo += 1)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Ad)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Diyetisyen.Kullanici.Ad) @Html.DisplayFor(modelItem => item.Diyetisyen.Kullanici.Soyad)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Ogun.Aciklama)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Paket.Aciklama)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.MenuTarih.Date)
                </td>
                <td>
                    @Html.ActionLink("Menu İçerik Görüntüle", "MenuIcerik", new { id = item.Id }, new { @class = "btn btn-warning" })
                </td>
            </tr>
        }

    </table>
</fieldset>

EveTeslimDiyetServis/Views/Asci/ListSiparisAlinan.cshtml
@model IEnumerable<ETDS.Models.Siparis>
@{
    ViewBag.Title = "ListSiparis";
    Layout = "~/Views/Shared/_LayoutAsci.cshtml";
}

<div>
    <fieldset>
        <legend>Alınan Siparişler</legend>
        <table class="table table-bordered">
            <tr>
                <th>
                    @Html.DisplayName("Sipariş No")
                </th>
                <th>
                    @Html.DisplayName("Paket(cal)")
                </th>
                <th>
                    @Html.DisplayName("Öğün")
                </th>
                <th>
                    @Html.DisplayName("İl")
                </th>
                <th>
                    @Html.DisplayName("Tarih")
                </th>
                <th>
                    @Html.DisplayName("Durum")
                </th>
                <th></th>
            </tr>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Id)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Paket.Aciklama)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Ogun.Aciklama)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Kullanici.Il.Ad)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Tarih)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.SiparisDurum.Durum)
                    </td>
                    <td>
                        @Html.ActionLink("Siparişi Onayla", "SiparisOnay", new { id = item.Id }, new { @class = "btn btn-info", data_toggle = "modal", data_target = "#siparisOnay", data_dismiss = "modal", data_backdrop = "static", data_keyboard = "false" })|
                        @Html.ActionLink("Kuryeye Gönder", "SiparisGonder", new { id = item.Id }, new { @class = "btn btn-warning" }) 
                    </td>
                </tr>
            }

        </table>
    </fieldset>
</div>
<div class="modal fade" tabindex="-1" role="dialog" id="siparisOnay">
    <div class="modal-dialog">
        <div class="modal-body">
            <div class="modal-content">
                @Html.Partial("SiparisOnay", new ETDS.Models.Siparis(), new ViewDataDictionary { { "Id", Model.GetEnumerator() } })
            </div>
        </div>
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

EveTeslimDiyetServis/Views/Asci/ListSiparisTamamlanan.cshtml
@model IEnumerable<ETDS.Models.Siparis>
@{
    ViewBag.Title = "ListSiparis";
    Layout = "~/Views/Shared/_LayoutAsci.cshtml";
}

<div>
    <fieldset>
        <legend>Tamamlanan Siparişler</legend>
        <table class="table table-bordered">
            <tr>
                <th>
                    @Html.DisplayName("Sipariş No")
                </th>
                <th>
                    @Html.DisplayName("Paket(cal)")
                </th>
                <th>
                    @Html.DisplayName("Öğün")
                </th>
                <th>
                    @Html.DisplayName("İl")
                </th>
                <th>
                    @Html.DisplayName("Tarih")
                </th>
                <th>
                    @Html.DisplayName("Durum")
                </th>
            </tr>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Id)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Paket.Aciklama)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Ogun.Aciklama)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Kullanici.Il.Ad)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Tarih)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.SiparisDurum.Durum)
                    </td>
                </tr>
            }

        </table>
    </fieldset>
</div>

EveTeslimDiyetServis/Views/Asci/MenuIcerik.cshtml
@model IEnumerable<ETDS.Models.YemekMenu>

@{
    ViewBag.Title = "YemekList";
    Layout = "~/Views/Shared/_LayoutDiyetisyen.cshtml";
}
<div class="col-md-12">
    <div class="col-md-8">
        <fieldset>
            <legend>@ViewBag.MenuAd Adlı Menüye Ait Yemekler</legend>
            <br />
            <br />
            <table class="table table-bordered table-striped">
                <tr>
                    <th>
                    </th>
                    <th>
                        @Html.DisplayName("Yemek")
                    </th>
                </tr>
                @{int rowNo = 0;}
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @(rowNo += 1)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Yemek.Ad)
                        </td>
                    </tr>
                }

            </table>
        </fieldset>
    </div>
</div>
<div class="col-md-offset-7">
    <a class="btn btn-info" href="@Url.Action("ListMenu","Asci")">Geri Dön</a>
</div>

EveTeslimDiyetServis/Views/Asci/SiparisGonder.cshtml
@model ETDS.Models.Siparis

@{
    ViewBag.Title = "SiparisGonder";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}


@using (Html.BeginForm("SiparisGonder", "Asci", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)


    <fieldset>
        <legend>Sipariş Gönder</legend>
        <div class="orm-group">
            <div class="alert alert-info" style="width:75%;">Lütfen sipariş numarasını ve dağıtımı yapacak kuryeyi seçiniz.</div>
        </div>
        <div class="form-group">
            <label class="control-label">Sipariş No</label>
            <div class="row">
                <div class="form-group">
                    <div class="col-md-5">
                        @Html.DropDownList("Id", (List<SelectListItem>)ViewBag.SiparisList, "Sipariş Seçiniz..", new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.Id)
                    </div>
                </div>
            </div>
        </div>
        <div class="form-group">
            <label class="control-label">Kurye</label>
            <div class="row">
                <div class="form-group">
                    <div class="col-md-5">
                        @Html.DropDownList("KuryeId", (List<SelectListItem>)ViewBag.KuryeList, "Kurye Seçiniz..", new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.KuryeId)
                    </div>
                </div>
            </div>
        </div>

        <br />
        <div class="form-group col-md-offset-3">
            <div class="row">
                <a href="@Url.Action("ListSiparisAlinan","Asci")" class="btn btn-default btn-large">İPTAL</a>    <input type="submit" value="EKLE" class="btn btn-primary btn-large" style="width:100px;" />
            </div>
        </div>
    </fieldset>
}

EveTeslimDiyetServis/Views/Asci/SiparisOnay.cshtml
@model ETDS.Models.Siparis
@using (Html.BeginForm("SiparisOnay", "Asci", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">Sipariş Onay</h3>
        </div>
        <div class="panel-body">
            <div class="form-group">
                <p>Alınmış olan siparişi onaylıyor musunuz ?</p>
                @Html.HiddenFor(model => model.Id)
            </div>

            <div class="pull-right clearfix">
                <input type="submit" value="ONAYLA" class="btn btn-primary btn-md" />  <a href="@Url.Action("ListSiparisAlinan", "Asci")" class="btn btn-default btn-md">İPTAL</a>
            </div>
        </div>
    </div>
}